stages:  
 - push
 - deploy
push:  
    stage: push  
    image: python:3.9  
    script:  

        
        - docker login --username=hesam80 --password=sa13801380
        - docker build -t simpleapps:v0.4  .
        - docker ps
        - docker tag simpleapp:v0.4 hesam80/simpleapps:latest
        - docker push hesam80/simpleappss:latest
  only:  
        - dev

deploy:  
    stage: deploy  
    image: python:3.5
    variables:  
        COLLECT_ERROR: 1  
    script:  
            - echo $TRAVIS_COMMIT
            - docker login --username=hesam80 --password=sa13801380
            - docker build -t simpleapps:v0.4 .
            - docker images
            - docker tag simpleapps:v0.4 hesam80/simpleappss:latest
            - docker push hesam80/simpleappss:latest
            - COLLECT_ERROR=True fandogh login --username hesam80 --password sa13801380
            - fandogh service apply -f simpleapps.yml
